# Generated by Django 2.1.7 on 2019-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_adi', models.CharField(max_length=80)),
                ('servis_tip', models.CharField(max_length=2)),
                ('servis_aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
